FROM node:24.5.0 AS dev-build

USER root

RUN apt-get update && apt-get install -y ca-certificates

# Copy package files first for better caching
COPY client/package*.json ./
RUN npm config set strict-ssl false && npm install @mui/material @emotion/react @emotion/styled @mui/x-date-pickers dayjs

WORKDIR /app

# Copy the rest of the application
COPY client/ ./

EXPOSE 3000
CMD ["npm", "run", "dev"]