FROM python:3.13.6 AS dev-build

RUN apt-get update && apt-get install -y
COPY server/requirements.txt ./requirements.txt
COPY server/src /src/
RUN UV_HTTP_TIMEOUT=3000 pip3 install uv && uv pip install --system -r requirements.txt
WORKDIR /src/
# ENTRYPOINT ["tail", "-f", "/dev/null"]