FROM ollama/ollama:0.5.8-rc7 AS dev-build

# Add your certificates
COPY ollama/ollama.crt /usr/local/share/ca-certificates/
COPY certs/ZscalerRootCA.crt /usr/local/share/ca-certificates/ZscalerRootCA.crt

# Install Let's Encrypt certificates
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/* \
	update-ca-certificates

COPY ollama/download-model.sh /tmp/download-model.sh

EXPOSE 11434

WORKDIR /tmp

RUN chmod +x download-model.sh \
    && ./download-model.sh
